// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceMonitor.WebApi.Data;

namespace PriceMonitor.WebApi.Data.Migrations
{
    [DbContext(typeof(MonitorContext))]
    [Migration("20210209172840_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PriceMonitor.WebApi.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<decimal>("CurrentFullValue")
                        .HasColumnType("money");

                    b.Property<decimal>("CurrentInCashValue")
                        .HasColumnType("money");

                    b.Property<decimal>("CurrentNormalValue")
                        .HasColumnType("money");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PriceMonitor.WebApi.Models.ItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<decimal>("FullValue")
                        .HasColumnType("money");

                    b.Property<decimal>("InCashValue")
                        .HasColumnType("money");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NormalValue")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("PriceMonitor.WebApi.Models.ItemHistory", b =>
                {
                    b.HasOne("PriceMonitor.WebApi.Models.Item", "Item")
                        .WithMany("History")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PriceMonitor.WebApi.Models.Item", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
